## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
from citipy import citipy
# Import API key
from config import g_key
#Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("weather_database/cities.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Puerto Ayora,EC,-0.7393,-90.3518,80.56,84,82,5.99,broken clouds
1,1,Faanui,PF,-16.4833,-151.7500,79.92,77,91,14.70,light rain
2,2,Kapaa,US,22.0752,-159.3190,69.78,88,1,3.49,clear sky
3,3,New Norfolk,AU,-42.7826,147.0587,39.70,85,33,2.98,scattered clouds
4,4,Umm Kaddadah,SD,13.6017,26.6876,102.49,10,36,10.83,scattered clouds

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 73
What is the maximum temperature you would like for your trip? 83

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Puerto Ayora,EC,-0.7393,-90.3518,80.56,84,82,5.99,broken clouds
1,1,Faanui,PF,-16.4833,-151.7500,79.92,77,91,14.70,light rain
7,7,Praya,CV,14.9215,-23.5087,82.94,54,20,16.11,few clouds
11,11,Labuhan,ID,-6.8844,112.2051,79.45,82,100,3.98,overcast clouds
13,13,Kimbe,PG,-5.5502,150.1429,75.65,95,42,5.53,scattered clouds
14,14,Souillac,MU,-20.5167,57.5167,74.35,78,10,7.11,clear sky
15,15,Rikitea,PF,-23.1203,-134.9692,74.25,83,100,17.16,moderate rain
16,16,Arraial Do Cabo,BR,-22.9661,-42.0278,78.66,78,75,11.50,broken clouds
29,29,Lorengau,PG,-2.0226,147.2712,81.34,83,100,9.64,overcast clouds
30,30,Vaini,TO,-21.2000,-175.2000,75.36,100,90,5.75,moderate rain

In [5]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                147
City                   147
Country                146
Lat                    147
Lng                    147
Max Temp               147
Humidity               147
Cloudiness             147
Wind Speed             147
Current Description    147
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = preferred_cities_df.dropna()
clean_df.tail(20)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
636,636,Kieta,PG,-6.2167,155.6333,77.83,86,72,3.76,light rain
637,637,Padang,ID,-0.9492,100.3543,77.13,89,74,3.91,moderate rain
638,638,Port-Gentil,GA,-0.7193,8.7815,79.20,83,57,17.16,broken clouds
639,639,Abu Samrah,SY,35.3029,37.1841,82.90,22,0,13.15,clear sky
643,643,Pentecoste,BR,-3.7928,-39.2703,82.67,40,11,8.59,few clouds
644,644,Pemba,MZ,-12.9740,40.5178,79.25,67,76,11.23,broken clouds
650,650,Malatya,TR,38.5000,38.0000,77.05,22,20,5.64,few clouds
651,651,Maceio,BR,-9.6658,-35.7353,81.84,74,75,12.33,broken clouds
653,653,Mweka,CD,-4.8500,21.5667,81.66,45,60,0.56,broken clouds
657,657,Buzuluk,RU,52.7807,52.2635,73.33,63,5,7.72,clear sky
662,662,Eyl,SO,7.9803,49.8164,80.60,78,98,21.74,overcast clouds
665,665,Hilton Head Island,US,32.2163,-80.7526,80.01,64,75,10.36,broken clouds
667,667,Kinablangan,PH,7.6947,126.5503,75.87,93,100,6.55,heavy intensity rain
668,668,Kiunga,PG,-6.1219,141.2906,74.53,91,100,2.37,overcast clouds
669,669,Kuliyapitiya,LK,7.4688,80.0401,78.24,92,62,6.17,broken clouds
673,673,Kendari,ID,-3.9450,122.4989,75.61,92,99,1.92,overcast clouds
679,679,Atbasar,KZ,51.8000,68.3333,75.22,43,27,11.79,scattered clouds
683,683,Totskoye,RU,52.5248,52.7623,73.78,63,31,8.50,scattered clouds
698,698,Wewak,PG,-3.5534,143.6268,80.80,84,99,11.05,overcast clouds
704,704,Crowley,US,30.2141,-92.3746,73.98,79,40,9.31,scattered clouds

In [7]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""

In [8]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key,
}

# 6b. Iterate through the hotel DataFrame 
for index, row in hotel_df.iterrows():
    # get lat, lng from df
    lat = row["Lat"]
    lng = row["Lng"]
    
    # 6c. Get latitude and longitude from DataFrame.
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")
hotel_df.head(10)

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Puerto Ayora,EC,80.56,broken clouds,-0.7393,-90.3518,Finch Bay Galapagos Hotel
1,Faanui,PF,79.92,light rain,-16.4833,-151.7500,Bora-Bora Pearl Beach Resort & Spa
7,Praya,CV,82.94,few clouds,14.9215,-23.5087,LT Aparthotel
11,Labuhan,ID,79.45,overcast clouds,-6.8844,112.2051,PT PPI Lamongan Tambak C
13,Kimbe,PG,75.65,scattered clouds,-5.5502,150.1429,Kimbe Bay Hotel
14,Souillac,MU,74.35,clear sky,-20.5167,57.5167,Shanti Maurice Resort & Spa
15,Rikitea,PF,74.25,moderate rain,-23.1203,-134.9692,Pension Maro'i
16,Arraial Do Cabo,BR,78.66,broken clouds,-22.9661,-42.0278,Pousada Porto Praia
29,Lorengau,PG,81.34,overcast clouds,-2.0226,147.2712,Lorengau Harbourside Hotel
30,Vaini,TO,75.36,moderate rain,-21.2000,-175.2000,Keleti Beach Resort

In [9]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df[hotel_df['Hotel Name'] != '']
clean_hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Puerto Ayora,EC,80.56,broken clouds,-0.7393,-90.3518,Finch Bay Galapagos Hotel
1,Faanui,PF,79.92,light rain,-16.4833,-151.7500,Bora-Bora Pearl Beach Resort & Spa
7,Praya,CV,82.94,few clouds,14.9215,-23.5087,LT Aparthotel
11,Labuhan,ID,79.45,overcast clouds,-6.8844,112.2051,PT PPI Lamongan Tambak C
13,Kimbe,PG,75.65,scattered clouds,-5.5502,150.1429,Kimbe Bay Hotel
14,Souillac,MU,74.35,clear sky,-20.5167,57.5167,Shanti Maurice Resort & Spa
15,Rikitea,PF,74.25,moderate rain,-23.1203,-134.9692,Pension Maro'i
16,Arraial Do Cabo,BR,78.66,broken clouds,-22.9661,-42.0278,Pousada Porto Praia
29,Lorengau,PG,81.34,overcast clouds,-2.0226,147.2712,Lorengau Harbourside Hotel
30,Vaini,TO,75.36,moderate rain,-21.2000,-175.2000,Keleti Beach Resort

In [10]:
# 8a. Create the output File (CSV)
output_data_file = "Vacation_Search/WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [11]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""
# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

In [12]:
# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]
# 11a. Add a marker layer for each city to the map. 
max_temp = clean_hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))